osx_instance:
  image: catalina-flutter

trail_task:
  trail_script:
    - echo "hi"
    - ls
    - flutter --version
mac_task:
    trail_mac_script:
      - xcodebuild -version
      - flutter --version
