osx_instance:
  image: catalina-flutter

task:
  name: trail
  trail_script:
    - echo "hi"
    - ls
    - flutter --version

task:
  name: mac_tsak
  trail_mac_script:
    - xcodebuild -version
    - flutter --version
