container:
  image: cirrusci/flutter:latest

trail_task:
  trail_script:
    - echo "hi"
    - ls
    - flutter --version
mac_task:
  osx_instance:
    image: catalina-flutter
    trail_mac_script:
      - xcodebuild -version
